import Head from "next/head";
import { useState } from "react";
import styles from "@component/styles/Home.module.css";
import AdminInput from "@component/components/AdminInput";
import YemekListesi from "@component/components/YemekListesi";

export default function Home() {
  const [goster, setGoster] = useState(false);
  const [text, setText] = useState("Yemek Listesini Göster");

  const toggle = () => {
    setGoster(!goster);
    const buttonText = goster
      ? "Yemek Listesini Göster"
      : "Yemek Listesini Gizle";
    setText(buttonText);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AdminInput />
        <button onClick={() => toggle()}>{text}</button>
        {goster && <YemekListesi />}
      </main>
    </>
  );
}
